// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmqzqtytuljfvdyzvlwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcXpxdHl0dWxqZnZkeXp2bHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDA0MDAsImV4cCI6MjA2NTQxNjQwMH0.9bMRtBXNh2x4FBbMEKskbvy2JtxJWrf8nFwgWN5cnZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);